# Generated by Django 6.0 on 2026-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmodel_name_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
