# Generated by Django 6.0 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='alt',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
