# Generated by Django 6.0 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanagermodel',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
