# Generated by Django 6.0 on 2026-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_ordermanagermodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermanagermodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ordermanagermodel',
            name='user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermanagermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
