# Generated by Django 6.0 on 2026-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
    ]
