# Generated by Django 6.0 on 2026-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='state',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='card',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='phone',
            field=models.CharField(default=23456, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
